### ISSUE TITLE
[1.12] [1.0.0] Crash due to java.lang.NoSuchFieldError: ITEMS

### ISSUE THREAD

**Issue by starg09** [InsomniaKitten/SmartHUD#1] opened 2017-06-24 00:04 UTC
[Crash Report](https://gist.github.com/starg09/68621ef96e156092f7fabdae71287486).

* Mod version: 1.0.0
* Minecraft Version: 1.12
* Forge build: 2348

**Comment by ChloeDawn** [comment] 2017-06-24 00:48
Cannot reproduce this in my development environment. Managed to reproduce on older Forge versions outside of dev, so it's not related to the latest Forge release.

**Comment by ChloeDawn** [comment] 2017-06-24 01:42
Fixed in [1.0.1](https://minecraft.curseforge.com/projects/smart-hud/files/2440474)

Well, I'm not using `ForgeRegistries.ITEMS.getValue()` to lookup items anymore.
I'm now using `Item.REGISTRY.getObject()` until the actual issue is resolved.

**Closed as completed by ChloeDawn** 2017-06-24 01:42 UTC
Labels: bug, high-priority
